# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d238d5e3b454c24591448f0cdc6e615bd075e727ef6291be071250f2a84a7725dd3c8cb113a5bfce2764fc1a6b6b3d144787d5e5721e59bd7d4e4fae70a109a4

test:
  secret_key_base: 66eb277e92724a655da109be29ebce4d759415fe47ee7bf7e49b80c49730bf66c29c38a3b8afd33fe9b583556b05d56ddce5a7a3025ffea5706b2a91b5ced68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
